
#端口号
server:
  port: 8080

spring:
  #应用名
  application:
    name: test4service
  #编码格式
  tomcat:
    uri-encoding: utf-8
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.98.39.115:3306/Test4?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zhou
    